[directories]
astcachedir => __VIGILIA_ASTERISK_VAR_DIR__/cache
astetcdir => __VIGILIA_ASTERISK_ETC_DIR__
astmoddir => /usr/local/asterisk/lib/asterisk/modules
astvarlibdir => __VIGILIA_ASTERISK_VAR_DIR__/lib
astdbdir => __VIGILIA_ASTERISK_VAR_DIR__/lib
astkeydir => __VIGILIA_ASTERISK_VAR_DIR__/keys
astdatadir => __VIGILIA_ASTERISK_VAR_DIR__/lib
astagidir => __VIGILIA_ASTERISK_VAR_DIR__/agi-bin
astspooldir => __VIGILIA_ASTERISK_VAR_DIR__/spool
astrundir => __VIGILIA_ASTERISK_VAR_DIR__/run
astlogdir => __VIGILIA_ASTERISK_VAR_DIR__/log
astsbindir => /usr/local/asterisk/sbin

[options]
runuser = __VIGILIA_RUNTIME_USER__
rungroup = __VIGILIA_RUNTIME_GROUP__
documentation_language = en_US
transmit_silence_during_record = yes
