[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[8001]
type=endpoint
context=from-vto
disallow=all
allow=alaw,ulaw
aors=8001
direct_media=no
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
identify_by=username,ip
media_use_received_transport=yes

[8001]
type=aor
max_contacts=1
remove_existing=yes

[8001-identify]
type=identify
endpoint=8001
match=192.168.100.108
