from __future__ import annotations

import os
import socket
import subprocess
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class BaresipHelloRuntimeConfig:
    workdir: Path
    local_user: str
    local_domain: str
    local_port: int
    greeting_text: str = "Hola, soy MatIA. Esta es una prueba de audio."
    voice: str = "Rocko (Español (México))"
    module_path: str = "/usr/local/lib/baresip/modules"

    @classmethod
    def from_env(cls, runtime_dir: Path) -> "BaresipHelloRuntimeConfig":
        local_domain = os.getenv("VIGILIA_HELLO_SIP_DOMAIN") or os.getenv("VIGILIA_SIP_LOCAL_DOMAIN")
        return cls(
            workdir=runtime_dir / "baresip-hello",
            local_user=os.getenv("VIGILIA_HELLO_SIP_USER", "door"),
            local_domain=local_domain or detect_lan_ip(),
            local_port=int(os.getenv("VIGILIA_HELLO_SIP_PORT", "5060")),
            greeting_text=os.getenv("VIGILIA_HELLO_TEXT", "Hola, soy MatIA. Esta es una prueba de audio."),
            voice=os.getenv("VIGILIA_HELLO_VOICE", "Rocko (Español (México))"),
            module_path=os.getenv("VIGILIA_BARESIP_MODULE_PATH", "/usr/local/lib/baresip/modules"),
        )


class BaresipHelloRuntimeBuilder:
    def __init__(self, config: BaresipHelloRuntimeConfig) -> None:
        self._config = config

    def prepare(self) -> dict[str, object]:
        self._config.workdir.mkdir(parents=True, exist_ok=True)
        audio_dir = self._config.workdir.parent / "baresip" / "audio"
        audio_dir.mkdir(parents=True, exist_ok=True)
        aiff_path = audio_dir / "hola-matia.aiff"
        wav_path = audio_dir / "hola-matia.wav"

        subprocess.run(
            ["say", "-v", self._config.voice, "-o", str(aiff_path), self._config.greeting_text],
            check=True,
        )
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-loglevel",
                "error",
                "-i",
                str(aiff_path),
                "-ar",
                "8000",
                "-ac",
                "1",
                "-acodec",
                "pcm_s16le",
                str(wav_path),
            ],
            check=True,
        )

        accounts_path = self._config.workdir / "accounts"
        config_path = self._config.workdir / "config"
        account_line = (
            f"<sip:{self._config.local_user}@{self._config.local_domain}:{self._config.local_port};transport=udp>;"
            f"regint=0;answermode=auto;audio_source=aufile,{wav_path}"
        )
        accounts_path.write_text(account_line + "\n", encoding="utf-8")
        config_path.write_text(self._build_config_text(wav_path), encoding="utf-8")

        return {
            "mode": "gds-hello-test",
            "workdir": str(self._config.workdir),
            "config_path": str(config_path),
            "accounts_path": str(accounts_path),
            "audio_file": str(wav_path),
            "captured_audio_file": str(self.captured_audio_path()),
            "account_line": account_line,
            "listen_uri": f"sip:{self._config.local_user}@{self._config.local_domain}:{self._config.local_port}",
            "run_command": ["baresip", "-s", "-f", str(self._config.workdir)],
            "process_capture_command": ["python3", "-m", "app.main", "--mode", "gds-capture-process"],
            "gds_call_target": f"{self._config.local_user}@{self._config.local_domain}",
        }

    def captured_audio_path(self) -> Path:
        return self._config.workdir / "gds-rx.wav"

    def _build_config_text(self, wav_path: Path) -> str:
        return "\n".join(
            [
                "# Auto-generated by VIGILIA for GDS hello audio tests.",
                f"module_path {self._config.module_path}",
                "module stdio.so",
                "module contact.so",
                "module menu.so",
                "module aufile.so",
                "module account.so",
                "module g711.so",
                "module auconv.so",
                "module auresamp.so",
                f"sip_listen {self._config.local_domain}:{self._config.local_port}",
                f"audio_source aufile,{wav_path}",
                f"audio_player aufile,{self._config.workdir / 'gds-rx.wav'}",
                "ausrc_srate 8000",
                "ausrc_channels 1",
                "auplay_srate 8000",
                "auplay_channels 1",
                "",
            ]
        )


def detect_lan_ip() -> str:
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as probe:
        try:
            probe.connect(("192.0.2.1", 9))
            candidate = probe.getsockname()[0]
            if not candidate.startswith("127."):
                return candidate
        except OSError:
            pass

    try:
        result = subprocess.run(["ifconfig"], check=True, capture_output=True, text=True)
    except (OSError, subprocess.CalledProcessError):
        return "127.0.0.1"

    for line in result.stdout.splitlines():
        stripped = line.strip()
        if not stripped.startswith("inet "):
            continue
        candidate = stripped.split()[1]
        if candidate.startswith("127."):
            continue
        if candidate.startswith(("10.", "172.", "192.168.")):
            return candidate
    return "127.0.0.1"
