from __future__ import annotations

from dataclasses import asdict
from pathlib import Path

from services.telephony.baresip_config import BaresipConfig
from services.telephony.sip_config import SipEndpointConfig
from services.telephony.sip_uri import build_sip_uri


class BaresipRuntimeBuilder:
    def __init__(
        self,
        baresip_config: BaresipConfig | None = None,
        sip_config: SipEndpointConfig | None = None,
    ) -> None:
        self._baresip_config = baresip_config or BaresipConfig.from_env()
        self._sip_config = sip_config or SipEndpointConfig(
            device_label="gds3725",
            local_user="vigilia",
            local_domain="127.0.0.1",
        )

    def build_account_line(self) -> str:
        local_uri = build_sip_uri(
            user=self._sip_config.local_user,
            domain=self._sip_config.local_domain,
            port=self._sip_config.local_port,
            transport=self._sip_config.transport,
        )
        return f"<{local_uri}>;regint=0"

    def build_config_text(self) -> str:
        return "\n".join(
            [
                "# Auto-generated by VIGILIA",
                "module_path modules",
                "module stdio.so",
                "module contact.so",
                "module menu.so",
                "module aubridge.so",
                "module aufile.so",
                "module account.so",
                "audio_player %s",
                "audio_source %s",
                "",
            ]
        ) % (self._baresip_config.audio_path, self._baresip_config.audio_path)

    def prepare(self) -> dict[str, object]:
        workdir = Path(self._baresip_config.workdir)
        config_path = Path(self._baresip_config.config_path)
        accounts_path = Path(self._baresip_config.accounts_path)
        audio_path = Path(self._baresip_config.audio_path)

        workdir.mkdir(parents=True, exist_ok=True)
        audio_path.mkdir(parents=True, exist_ok=True)
        config_path.parent.mkdir(parents=True, exist_ok=True)
        accounts_path.parent.mkdir(parents=True, exist_ok=True)

        config_path.write_text(self.build_config_text(), encoding="utf-8")
        accounts_path.write_text(self.build_account_line() + "\n", encoding="utf-8")

        return {
            "baresip": asdict(self._baresip_config),
            "sip": asdict(self._sip_config),
            "config_path": str(config_path),
            "accounts_path": str(accounts_path),
            "audio_path": str(audio_path),
            "account_line": self.build_account_line(),
        }
