[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[vto]
type=endpoint
context=from-vto
disallow=all
allow=alaw
aors=vto
direct_media=no
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
identify_by=ip

[vto]
type=aor
max_contacts=1

[vto-identify]
type=identify
endpoint=vto
match=192.168.100.108
