#!/bin/bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export VIGILIA_PROJECT_DIR="${VIGILIA_PROJECT_DIR:-$PROJECT_DIR}"
export VIGILIA_RUNTIME_DIR="${VIGILIA_RUNTIME_DIR:-$PROJECT_DIR/.runtime}"
export VIGILIA_RUN_DIR="${VIGILIA_RUN_DIR:-$VIGILIA_RUNTIME_DIR/run}"
export VIGILIA_LOG_DIR="${VIGILIA_LOG_DIR:-$VIGILIA_RUNTIME_DIR/logs}"
export VIGILIA_AUDIO_DIR="${VIGILIA_AUDIO_DIR:-$VIGILIA_RUNTIME_DIR/audio}"
export VIGILIA_ASTERISK_DIR="${VIGILIA_ASTERISK_DIR:-$VIGILIA_RUNTIME_DIR/asterisk}"
export VIGILIA_ASTERISK_ETC_DIR="${VIGILIA_ASTERISK_ETC_DIR:-$VIGILIA_ASTERISK_DIR/etc/asterisk}"
export VIGILIA_ASTERISK_VAR_DIR="${VIGILIA_ASTERISK_VAR_DIR:-$VIGILIA_ASTERISK_DIR/var}"
export VIGILIA_INFERENCE_SOCKET="${VIGILIA_INFERENCE_SOCKET:-$VIGILIA_RUN_DIR/vigilia_inference.sock}"
export VIGILIA_INFERENCE_LOG="${VIGILIA_INFERENCE_LOG:-$VIGILIA_LOG_DIR/vigilia_inference.log}"
export VIGILIA_DEFAULT_AUDIO_PATH="${VIGILIA_DEFAULT_AUDIO_PATH:-$VIGILIA_AUDIO_DIR/vecino.wav}"
export VIGILIA_DEFAULT_RESPONSE_AUDIO_PATH="${VIGILIA_DEFAULT_RESPONSE_AUDIO_PATH:-$VIGILIA_AUDIO_DIR/ia_dice.wav}"
export VIGILIA_PLAY_RESPONSE_LOCALLY="${VIGILIA_PLAY_RESPONSE_LOCALLY:-1}"
export VIGILIA_PROMPT_AUDIO_BASE="${VIGILIA_PROMPT_AUDIO_BASE:-$VIGILIA_AUDIO_DIR/vigilia_prompt}"
export VIGILIA_LISTEN_AUDIO_BASE="${VIGILIA_LISTEN_AUDIO_BASE:-$VIGILIA_AUDIO_DIR/vigilia_listen}"
export VIGILIA_ASTERISK_LOG_PATH="${VIGILIA_ASTERISK_LOG_PATH:-$VIGILIA_LOG_DIR/vigilia_asterisk.log}"

mkdir -p \
  "$VIGILIA_RUNTIME_DIR" \
  "$VIGILIA_RUN_DIR" \
  "$VIGILIA_LOG_DIR" \
  "$VIGILIA_AUDIO_DIR" \
  "$VIGILIA_ASTERISK_ETC_DIR" \
  "$VIGILIA_ASTERISK_VAR_DIR"
