#!/bin/bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export VIGILIA_PROJECT_DIR="${VIGILIA_PROJECT_DIR:-$PROJECT_DIR}"
export VIGILIA_RUNTIME_DIR="${VIGILIA_RUNTIME_DIR:-$PROJECT_DIR/.runtime}"
export VIGILIA_RUN_DIR="${VIGILIA_RUN_DIR:-$VIGILIA_RUNTIME_DIR/run}"
export VIGILIA_LOG_DIR="${VIGILIA_LOG_DIR:-$VIGILIA_RUNTIME_DIR/logs}"
export VIGILIA_AUDIO_DIR="${VIGILIA_AUDIO_DIR:-$VIGILIA_RUNTIME_DIR/audio}"
export VIGILIA_ASTERISK_DIR="${VIGILIA_ASTERISK_DIR:-$VIGILIA_RUNTIME_DIR/asterisk}"
export VIGILIA_ASTERISK_ETC_DIR="${VIGILIA_ASTERISK_ETC_DIR:-$VIGILIA_ASTERISK_DIR/etc/asterisk}"
export VIGILIA_ASTERISK_VAR_DIR="${VIGILIA_ASTERISK_VAR_DIR:-$VIGILIA_ASTERISK_DIR/var}"
export VIGILIA_INFERENCE_SOCKET="${VIGILIA_INFERENCE_SOCKET:-$VIGILIA_RUN_DIR/vigilia_inference.sock}"
export VIGILIA_INFERENCE_LOG="${VIGILIA_INFERENCE_LOG:-$VIGILIA_LOG_DIR/vigilia_inference.log}"
export VIGILIA_FACE_SERVICE_SOCKET="${VIGILIA_FACE_SERVICE_SOCKET:-/tmp/vigilia_face.sock}"
export VIGILIA_FACE_SERVICE_LOG="${VIGILIA_FACE_SERVICE_LOG:-$VIGILIA_LOG_DIR/vigilia_face.log}"
export VIGILIA_DEFAULT_AUDIO_PATH="${VIGILIA_DEFAULT_AUDIO_PATH:-$VIGILIA_AUDIO_DIR/vecino.wav}"
export VIGILIA_DEFAULT_RESPONSE_AUDIO_PATH="${VIGILIA_DEFAULT_RESPONSE_AUDIO_PATH:-$VIGILIA_AUDIO_DIR/ia_dice.wav}"
export VIGILIA_HELLO_AUDIO_PATH="${VIGILIA_HELLO_AUDIO_PATH:-$VIGILIA_AUDIO_DIR/vigilia_hello.wav}"
export VIGILIA_RETRY_AUDIO_PATH="${VIGILIA_RETRY_AUDIO_PATH:-$VIGILIA_AUDIO_DIR/vigilia_retry.wav}"
export VIGILIA_VTO_LOCAL_HELLO_TEXT="${VIGILIA_VTO_LOCAL_HELLO_TEXT:-Hola}"
export VIGILIA_HELLO_PLAYBACK_RATE="${VIGILIA_HELLO_PLAYBACK_RATE:-1.0}"
export VIGILIA_PLAY_RESPONSE_LOCALLY="${VIGILIA_PLAY_RESPONSE_LOCALLY:-1}"
export VIGILIA_PREFER_DIRECT_LOCAL_TTS="${VIGILIA_PREFER_DIRECT_LOCAL_TTS:-1}"
export VIGILIA_ENABLE_LOCAL_FOLLOWUP_CAPTURE="${VIGILIA_ENABLE_LOCAL_FOLLOWUP_CAPTURE:-1}"
export VIGILIA_LOCAL_FOLLOWUP_AUDIO_DEVICE="${VIGILIA_LOCAL_FOLLOWUP_AUDIO_DEVICE:-:1}"
export VIGILIA_LOCAL_FOLLOWUP_DURATION_SECONDS="${VIGILIA_LOCAL_FOLLOWUP_DURATION_SECONDS:-4}"
export VIGILIA_DECISION_MODEL="${VIGILIA_DECISION_MODEL:-vigilia-mini}"
export VIGILIA_SPOKEN_RESPONSE_MODEL="${VIGILIA_SPOKEN_RESPONSE_MODEL:-$VIGILIA_DECISION_MODEL}"
export VIGILIA_DISABLE_VTO_SNAPSHOT="${VIGILIA_DISABLE_VTO_SNAPSHOT:-0}"
export VIGILIA_VTO_SNAPSHOT_TIMEOUT_SECONDS="${VIGILIA_VTO_SNAPSHOT_TIMEOUT_SECONDS:-5}"
export VIGILIA_PROMPT_AUDIO_BASE="${VIGILIA_PROMPT_AUDIO_BASE:-$VIGILIA_AUDIO_DIR/vigilia_prompt}"
export VIGILIA_LISTEN_AUDIO_BASE="${VIGILIA_LISTEN_AUDIO_BASE:-$VIGILIA_AUDIO_DIR/vigilia_listen}"
export VIGILIA_ASTERISK_LOG_PATH="${VIGILIA_ASTERISK_LOG_PATH:-$VIGILIA_LOG_DIR/vigilia_asterisk.log}"

mkdir -p \
  "$VIGILIA_RUNTIME_DIR" \
  "$VIGILIA_RUN_DIR" \
  "$VIGILIA_LOG_DIR" \
  "$VIGILIA_AUDIO_DIR" \
  "$VIGILIA_ASTERISK_ETC_DIR" \
  "$VIGILIA_ASTERISK_VAR_DIR"
